# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
  - 3.4
before_install:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; curl http://python-distribute.org/distribute_setup.py | sudo python3; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; sudo pip3 install -e git+https://github.com/gevent/gevent.git#egg=gevent; fi
install:
    python setup.py install
script:
    py.test